// Generated by gencpp from file franka_control/info.msg
// DO NOT EDIT!


#ifndef FRANKA_CONTROL_MESSAGE_INFO_H
#define FRANKA_CONTROL_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_control
{
template <class ContainerAllocator>
struct info_
{
  typedef info_<ContainerAllocator> Type;

  info_()
    : num(0.0)
    , receive()  {
    }
  info_(const ContainerAllocator& _alloc)
    : num(0.0)
    , receive(_alloc)  {
  (void)_alloc;
    }



   typedef float _num_type;
  _num_type num;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _receive_type;
  _receive_type receive;





  typedef boost::shared_ptr< ::franka_control::info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_control::info_<ContainerAllocator> const> ConstPtr;

}; // struct info_

typedef ::franka_control::info_<std::allocator<void> > info;

typedef boost::shared_ptr< ::franka_control::info > infoPtr;
typedef boost::shared_ptr< ::franka_control::info const> infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_control::info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_control::info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_control::info_<ContainerAllocator1> & lhs, const ::franka_control::info_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.receive == rhs.receive;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_control::info_<ContainerAllocator1> & lhs, const ::franka_control::info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_control::info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_control::info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_control::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_control::info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_control::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_control::info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_control::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c7aec7e51da1bf8a758e5a4abe8452d";
  }

  static const char* value(const ::franka_control::info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c7aec7e51da1bf8ULL;
  static const uint64_t static_value2 = 0xa758e5a4abe8452dULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_control::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_control/info";
  }

  static const char* value(const ::franka_control::info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_control::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 num\n"
"float32[] receive\n"
;
  }

  static const char* value(const ::franka_control::info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_control::info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.receive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_control::info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_control::info_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<float>::stream(s, indent + "  ", v.num);
    s << indent << "receive[]" << std::endl;
    for (size_t i = 0; i < v.receive.size(); ++i)
    {
      s << indent << "  receive[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.receive[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_CONTROL_MESSAGE_INFO_H
