// Generated by gencpp from file franka_msgs/SetEEFrameRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETEEFRAMEREQUEST_H
#define FRANKA_MSGS_MESSAGE_SETEEFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_msgs
{
template <class ContainerAllocator>
struct SetEEFrameRequest_
{
  typedef SetEEFrameRequest_<ContainerAllocator> Type;

  SetEEFrameRequest_()
    : NE_T_EE()  {
      NE_T_EE.assign(0.0);
  }
  SetEEFrameRequest_(const ContainerAllocator& _alloc)
    : NE_T_EE()  {
  (void)_alloc;
      NE_T_EE.assign(0.0);
  }



   typedef boost::array<double, 16>  _NE_T_EE_type;
  _NE_T_EE_type NE_T_EE;





  typedef boost::shared_ptr< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEEFrameRequest_

typedef ::franka_msgs::SetEEFrameRequest_<std::allocator<void> > SetEEFrameRequest;

typedef boost::shared_ptr< ::franka_msgs::SetEEFrameRequest > SetEEFrameRequestPtr;
typedef boost::shared_ptr< ::franka_msgs::SetEEFrameRequest const> SetEEFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator1> & lhs, const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.NE_T_EE == rhs.NE_T_EE;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator1> & lhs, const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cddf0858e7d540f5bcee9d813a7550a2";
  }

  static const char* value(const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcddf0858e7d540f5ULL;
  static const uint64_t static_value2 = 0xbcee9d813a7550a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_msgs/SetEEFrameRequest";
  }

  static const char* value(const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[16] NE_T_EE\n"
;
  }

  static const char* value(const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NE_T_EE);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEEFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_msgs::SetEEFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_msgs::SetEEFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "NE_T_EE[]" << std::endl;
    for (size_t i = 0; i < v.NE_T_EE.size(); ++i)
    {
      s << indent << "  NE_T_EE[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.NE_T_EE[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETEEFRAMEREQUEST_H
