// Generated by gencpp from file franka_msgs/SetEEFrame.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETEEFRAME_H
#define FRANKA_MSGS_MESSAGE_SETEEFRAME_H

#include <ros/service_traits.h>


#include <franka_msgs/SetEEFrameRequest.h>
#include <franka_msgs/SetEEFrameResponse.h>


namespace franka_msgs
{

struct SetEEFrame
{

typedef SetEEFrameRequest Request;
typedef SetEEFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEEFrame
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetEEFrame > {
  static const char* value()
  {
    return "459aea8fa6dbdd34ba4bc52d3eddbacf";
  }

  static const char* value(const ::franka_msgs::SetEEFrame&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetEEFrame > {
  static const char* value()
  {
    return "franka_msgs/SetEEFrame";
  }

  static const char* value(const ::franka_msgs::SetEEFrame&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetEEFrameRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetEEFrame >
template<>
struct MD5Sum< ::franka_msgs::SetEEFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetEEFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetEEFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetEEFrameRequest> should match
// service_traits::DataType< ::franka_msgs::SetEEFrame >
template<>
struct DataType< ::franka_msgs::SetEEFrameRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetEEFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetEEFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetEEFrameResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetEEFrame >
template<>
struct MD5Sum< ::franka_msgs::SetEEFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetEEFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetEEFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetEEFrameResponse> should match
// service_traits::DataType< ::franka_msgs::SetEEFrame >
template<>
struct DataType< ::franka_msgs::SetEEFrameResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetEEFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetEEFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETEEFRAME_H
