// Generated by gencpp from file franka_msgs/SetForceTorqueCollisionBehavior.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H
#define FRANKA_MSGS_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H

#include <ros/service_traits.h>


#include <franka_msgs/SetForceTorqueCollisionBehaviorRequest.h>
#include <franka_msgs/SetForceTorqueCollisionBehaviorResponse.h>


namespace franka_msgs
{

struct SetForceTorqueCollisionBehavior
{

typedef SetForceTorqueCollisionBehaviorRequest Request;
typedef SetForceTorqueCollisionBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceTorqueCollisionBehavior
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehavior > {
  static const char* value()
  {
    return "b1e592d1b6960bc05e6e3cba1eb02349";
  }

  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehavior&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetForceTorqueCollisionBehavior > {
  static const char* value()
  {
    return "franka_msgs/SetForceTorqueCollisionBehavior";
  }

  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehaviorRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehavior >
template<>
struct MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetForceTorqueCollisionBehaviorRequest> should match
// service_traits::DataType< ::franka_msgs::SetForceTorqueCollisionBehavior >
template<>
struct DataType< ::franka_msgs::SetForceTorqueCollisionBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehaviorResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehavior >
template<>
struct MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetForceTorqueCollisionBehaviorResponse> should match
// service_traits::DataType< ::franka_msgs::SetForceTorqueCollisionBehavior >
template<>
struct DataType< ::franka_msgs::SetForceTorqueCollisionBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetForceTorqueCollisionBehavior >::value();
  }
  static const char* value(const ::franka_msgs::SetForceTorqueCollisionBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETFORCETORQUECOLLISIONBEHAVIOR_H
