// Generated by gencpp from file franka_msgs/SetJointImpedance.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETJOINTIMPEDANCE_H
#define FRANKA_MSGS_MESSAGE_SETJOINTIMPEDANCE_H

#include <ros/service_traits.h>


#include <franka_msgs/SetJointImpedanceRequest.h>
#include <franka_msgs/SetJointImpedanceResponse.h>


namespace franka_msgs
{

struct SetJointImpedance
{

typedef SetJointImpedanceRequest Request;
typedef SetJointImpedanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointImpedance
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetJointImpedance > {
  static const char* value()
  {
    return "f11c4defa2a13040512214f9d77dc982";
  }

  static const char* value(const ::franka_msgs::SetJointImpedance&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetJointImpedance > {
  static const char* value()
  {
    return "franka_msgs/SetJointImpedance";
  }

  static const char* value(const ::franka_msgs::SetJointImpedance&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetJointImpedanceRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetJointImpedance >
template<>
struct MD5Sum< ::franka_msgs::SetJointImpedanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_msgs::SetJointImpedanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetJointImpedanceRequest> should match
// service_traits::DataType< ::franka_msgs::SetJointImpedance >
template<>
struct DataType< ::franka_msgs::SetJointImpedanceRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_msgs::SetJointImpedanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetJointImpedanceResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetJointImpedance >
template<>
struct MD5Sum< ::franka_msgs::SetJointImpedanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_msgs::SetJointImpedanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetJointImpedanceResponse> should match
// service_traits::DataType< ::franka_msgs::SetJointImpedance >
template<>
struct DataType< ::franka_msgs::SetJointImpedanceResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetJointImpedance >::value();
  }
  static const char* value(const ::franka_msgs::SetJointImpedanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETJOINTIMPEDANCE_H
