// Generated by gencpp from file franka_msgs/SetKFrame.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETKFRAME_H
#define FRANKA_MSGS_MESSAGE_SETKFRAME_H

#include <ros/service_traits.h>


#include <franka_msgs/SetKFrameRequest.h>
#include <franka_msgs/SetKFrameResponse.h>


namespace franka_msgs
{

struct SetKFrame
{

typedef SetKFrameRequest Request;
typedef SetKFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetKFrame
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetKFrame > {
  static const char* value()
  {
    return "11b22d30e6a11a7b51828be575a77359";
  }

  static const char* value(const ::franka_msgs::SetKFrame&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetKFrame > {
  static const char* value()
  {
    return "franka_msgs/SetKFrame";
  }

  static const char* value(const ::franka_msgs::SetKFrame&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetKFrameRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetKFrame >
template<>
struct MD5Sum< ::franka_msgs::SetKFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetKFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetKFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetKFrameRequest> should match
// service_traits::DataType< ::franka_msgs::SetKFrame >
template<>
struct DataType< ::franka_msgs::SetKFrameRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetKFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetKFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetKFrameResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetKFrame >
template<>
struct MD5Sum< ::franka_msgs::SetKFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetKFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetKFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetKFrameResponse> should match
// service_traits::DataType< ::franka_msgs::SetKFrame >
template<>
struct DataType< ::franka_msgs::SetKFrameResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetKFrame >::value();
  }
  static const char* value(const ::franka_msgs::SetKFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETKFRAME_H
