// Generated by gencpp from file franka_msgs/SetLoad.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETLOAD_H
#define FRANKA_MSGS_MESSAGE_SETLOAD_H

#include <ros/service_traits.h>


#include <franka_msgs/SetLoadRequest.h>
#include <franka_msgs/SetLoadResponse.h>


namespace franka_msgs
{

struct SetLoad
{

typedef SetLoadRequest Request;
typedef SetLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLoad
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetLoad > {
  static const char* value()
  {
    return "c9a8ec436164dd9cbc1e5e137d358e0b";
  }

  static const char* value(const ::franka_msgs::SetLoad&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetLoad > {
  static const char* value()
  {
    return "franka_msgs/SetLoad";
  }

  static const char* value(const ::franka_msgs::SetLoad&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetLoadRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetLoad >
template<>
struct MD5Sum< ::franka_msgs::SetLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetLoad >::value();
  }
  static const char* value(const ::franka_msgs::SetLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetLoadRequest> should match
// service_traits::DataType< ::franka_msgs::SetLoad >
template<>
struct DataType< ::franka_msgs::SetLoadRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetLoad >::value();
  }
  static const char* value(const ::franka_msgs::SetLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetLoadResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetLoad >
template<>
struct MD5Sum< ::franka_msgs::SetLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetLoad >::value();
  }
  static const char* value(const ::franka_msgs::SetLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetLoadResponse> should match
// service_traits::DataType< ::franka_msgs::SetLoad >
template<>
struct DataType< ::franka_msgs::SetLoadResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetLoad >::value();
  }
  static const char* value(const ::franka_msgs::SetLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETLOAD_H
